User.create!(name:  "Чудомир Ченков",
             email: "admin1234@example.com",
             password:              "foobar",
             password_confirmation: "foobar",
             admin: true,
             activated: true,
             activated_at: Time.zone.now,
             number: 15,
             klas: 8,
             section: 'A')

 User.create!(name:  "Николай Миланов",
              email: "use123r@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')

 User.create!(name:  "Кристиян Стоименов",
              email: "use123r1@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')  


 User.create!(name:  "Антоний Златаров",
              email: "as@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')  

 User.create!(name:  "Симеон Георгиев",
              email: "gma@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')  
 User.create!(name:  "Любомир",
              email: "use1mam@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')
 User.create!(name:  "Димитър Николов",
              email: "use2@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')
 User.create!(name:  "Иван Милев",
              email: "use3@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')  
 User.create!(name:  "Виктор Колев",
              email: "use4@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A') 
 User.create!(name:  "Венцислав Ташев",
              email: "use5@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A') 
 User.create!(name:  "Телерик",
              email: "use6@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A') 
 User.create!(name:  "Антонио Миндов",
              email: "use7@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A') 
 User.create!(name:  "Александър Карапенев",
              email: "us6e@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A') 
 User.create!(name:  "Ангел Йорданов",
              email: "u62se@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')  
 User.create!(name:  "Александър Велинов",
              email: "use72@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')
 User.create!(name:  "Николета Далакчиева",
              email: "use12@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A') 
 User.create!(name:  "Иво Стратев",
              email: "us112e@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')  
User.create!(name:  "  ",
              email: "orwq@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A') 
User.create!(name:  "Жанет Хаджиангелова",
              email: "masd@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A') 
User.create!(name:  "Мария Стоянова",
              email: "mama@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A') 
User.create!(name:  "Георги Данчев",
              email: "addd@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A') 
User.create!(name:  "Димитър Кацаров",
              email: "qzz@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')
User.create!(name:  "Владимир Младенов",
              email: "maikagi@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A') 
User.create!(name:  "Марина Тихова",
              email: "nashtati@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A') 
User.create!(name:  "Лъчезар Младенов",
              email: "bashtati@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')
User.create!(name:  "Андреа Георгиева",
              email: "andrea@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')
User.create!(name:  "Николай Рангелов",
              email: "nikito@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')
User.create!(name:  "Калин Карев",
              email: "kalinka@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')
User.create!(name:  "Светлин Йорданов",
              email: "svetlomie@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')
User.create!(name:  "Теодор Добрев",
              email: "egatiqkata09@example.com",
              password:              "foobar",
              password_confirmation: "foobar",
              activated: true,
              activated_at: Time.zone.now,
              number: 1,
              klas: 1,
              section: 'A')

Team.create!(name: "ALPHA", members_id: ["1"], technologies: ["Python", "GML"], project_desc: "Приложение, което ще направи живота на хората по-здравословен .", captain_id: 1, room: 13)
Team.create!(name: "ASDF UNICORNS", members_id: ["2", "19", "20","21", "22"], technologies: ["C++", "SDL", "PHP", "JavaScript", "HTML", "C#", "CSS", "mySQL", "Unity"], project_desc: "Правим тамгочи-дърво с цел да подпомогнем саденето на дърветата и опазването на околната среда.", captain_id: 2, room:13)
Team.create!(name: "az aum na stol", members_id: ["3"], captain_id: 3, room:13)
Team.create!(name: "Begginers", members_id: ["4"], captain_id: 4, room:14, project_desc: "Включване на точки за достъп чрез манхатанско разстояние.", technologies: ["JavaScript", "HTML"])
Team.create!(name: "Error 404: Name not found", members_id: ["5"], captain_id: 5, room:14, project_desc: "Нещо интересно и сложно... много сложно... чак не мога да го опиша, което ще плени сърцата на всички.")
Team.create!(name: "Fanatic", members_id: ["6"], captain_id: 6, room:14, project_desc: "Изненада")
Team.create!(name: "For Code Sake", members_id: ["7"], captain_id: 7, room:15, technologies: ["JavaScript", "CSS", "XML", "Java", "Objective-C"],project_desc: "Да кажем само, че ще сложим партито в джобовете на хората.")
Team.create!(name: "Heroes & Zeros", members_id: ["8"], captain_id: 8, room:15, technologies: ["SQL", "PHP", "HTML"],project_desc: "Това ще бъде сайт в който ще може да продавате и купувате учебници директно от учениците.")
Team.create!(name: "kakvo pravim tuka?", members_id: ["9"], captain_id: 9, room:15, project_desc: "Изненада! Все още няма да разкриваме идеята на проекта.")
Team.create!(name: "P2W", members_id: ["10"], captain_id: 10, room:43, project_desc: "Unity 2D Game", technologies: ["Unity3D", "C#"])
Team.create!(name: "PEEEEEEEE6O", members_id: ["11"], captain_id: 11, room:43)
Team.create!(name: "R&T", members_id: ["12"], captain_id: 12, room:43, project_desc: "Чрез нашия сайт потребителите ни ще могат да организират озеленяване на околната местност като показват на други потребители къде има нужда от засаждане на дръвчета или да видят къде има нужда от дръвчета и отидат да посадят.", technologies: ["HTML", "CSS", "JavaScript", "PHP", "Google Maps API", "Ruby on Rails"])
Team.create!(name: "Sa60 & Marto", members_id: ["13"], captain_id: 13, room:44, project_desc: "Ние от отбор Sa6o & Marto ще напавим проект , който да показва столичните кошчета , за да не се чудите къде да изхвърляте буклука си.", technologies: ["HTML"])
Team.create!(name: "The rabbits", members_id: ["14"], captain_id: 14, room:44)
Team.create!(name: "The TANKS", members_id: ["15", "26", "27", "28", "29", "30"], captain_id: 15, room:44, project_desc: "Система за четене на QR кодове, която е свързана с база данни, където са записани подробни данни за пациенти в болници.")
Team.create!(name: "Walking Chaos", members_id: ["16", "23", "24", "25"], captain_id: 16, room:45)
Team.create!(name: "Няма Значение", members_id: ["17"], captain_id: 17, room:45, project_desc: "Организацията на facebook events + форматът на kickstarter + формата за комуникация на slack.", technologies: ["Django", "Angular", "SPA with Bottstrap"])
Team.create!(name: "ВеликитеКомпютърниСпециалисти", room:45, project_desc: "Платформа за сигнализиране на изоставени коли.", technologies: ["HTML", "PHP", "CSS"], members_id: ["18"], captain_id: 18)
